

export const CONST = {
    ADD_CARD: "ADD_CARD",
    ADD_LIST: 'ADD_LIST',
    DND: "DND",
    EDIT_CARD_TITLE: "EDIT_CARD_TITLE",
    EDIT_LIST_TITLE:"EDIT_LIST_TITLE",
    DELETE_CARD: "DELETE_CARD",
    DELETE_LIST: "DELETE_LIST",
}

